### ISSUE TITLE
Get it work on Ubuntu20.10 smoothly

### ISSUE THREAD

**Issue by TomAPU** [pathtofile/bad-bpf#2]
Hello, I'm a beginner in eBPF field and after several struggling, I managed to get it work on my Ubuntu 20.10. 
So I assume that there is some information needed for beginners like me, and it would be great if some of it can be added to README.md

# Clone the project
First of all, to clone the project, the command worked for me is this:
```bash
git clone  https://github.com/pathtofile/bad-bpf.git --recusrive
```
the sequence of  "--recursive" actually matters.

# Install needed libraries and tools first
 Install all these needed stuffs by this command
```bash
apt install build-essential clang-11 libelf-dev zlib1g-dev libbfd-dev libcap-dev libbfd-dev  linux-tools-common linux-tools-generic
```
I didn't find "libfd-dev" provided in README.md, so I guess it is "libbfd-dev"

# generate vmlinux.h locally with bpftool
The  vmlinux.h provided occurred erros during compiling if you use Ubuntu20.10 like me.
So generating one locally is needed.
```bash
cd bad-bpf/src/
bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
```

# change clang versions in Makefile
This project work against clang-11, and I didn't find easy to to swtich clang version, so changing contents in Makefile while compiling might be a plausible option

Change contents in Makefile from
```
CLANG ?= clang
LLVM_STRIP ?= llvm-strip
```
to
```
CLANG ?= clang-11
LLVM_STRIP ?= llvm-strip-11
```
# happy compiling
```
make
```

**Comment by pathtofile** [comment]
Great feedback, thanks! I've updated things with your suggestions :-)
