### ISSUE TITLE
error in backend: Unsupported dynamic stack allocation

### ISSUE THREAD

**Issue by yaunsky** [pathtofile/bad-bpf#3]
**Cloned code cannot dynamically allocate addresses during compilation. What is the reason for this？**

pidhide.bpf.c:57:21: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
const volatile char pid_to_hide[max_pid_len];
                    ^
**fatal error: error in backend: Unsupported dynamic stack allocation**
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang -g -O2 -target bpf -D__TARGET_ARCH_x86 -I.output -idirafter /usr/local/include -idirafter /usr/lib/llvm-12/lib/clang/12.0.1/include -idirafter /usr/include/x86_64-linux-gnu -idirafter /usr/include -c pidhide.bpf.c -o .output/pidhide.bpf.o
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'pidhide.bpf.c'.
4.	Running pass 'BPF DAG->DAG Pattern Instruction Selection' on function '@handle_getdents_exit'
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
/lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamEi+0x31)[0x7fa81870d871]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm3sys17RunSignalHandlersEv+0x50)[0x7fa81870b9a0]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm3sys15CleanupOnSignalEm+0x100)[0x7fa81870cf00]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(+0xc746ba)[0x7fa81865b6ba]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(+0xc7465b)[0x7fa81865b65b]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm3sys7Process4ExitEib+0x27)[0x7fa818708047]
clang[0x412dc0]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm18report_fatal_errorERKNS_5TwineEb+0x122)[0x7fa818667ab2]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(+0xc80986)[0x7fa818667986]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(+0x2a4e68f)[0x7fa81a43568f]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(+0x130679b)[0x7fa818ced79b]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm12SelectionDAG8LegalizeEv+0x1a5)[0x7fa818cecd45]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm16SelectionDAGISel17CodeGenAndEmitDAGEv+0x48d)[0x7fa818e2ce9d]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm16SelectionDAGISel20SelectAllBasicBlocksERKNS_8FunctionE+0x185a)[0x7fa818e2c40a]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm16SelectionDAGISel20runOnMachineFunctionERNS_15MachineFunctionE+0x796)[0x7fa818e29f96]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm19MachineFunctionPass13runOnFunctionERNS_8FunctionE+0xfe)[0x7fa818a2f60e]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE+0x3a0)[0x7fa8188414f0]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE+0x33)[0x7fa8188470a3]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x3a8)[0x7fa818841af8]
/lib/x86_64-linux-gnu/libclang-cpp.so.12(_ZN5clang17EmitBackendOutputERNS_17DiagnosticsEngineERKNS_19HeaderSearchOptionsERKNS_14CodeGenOptionsERKNS_13TargetOptionsERKNS_11LangOptionsERKN4llvm10DataLayoutEPNSE_6ModuleENS_13BackendActionESt10unique_ptrINSE_17raw_pwrite_streamESt14default_deleteISM_EE+0x2dc6)[0x7fa81eaabac6]
/lib/x86_64-linux-gnu/libclang-cpp.so.12(+0x1856fae)[0x7fa81ed58fae]
/lib/x86_64-linux-gnu/libclang-cpp.so.12(_ZN5clang8ParseASTERNS_4SemaEbb+0x254)[0x7fa81de43d34]
/lib/x86_64-linux-gnu/libclang-cpp.so.12(_ZN5clang13CodeGenAction13ExecuteActionEv+0x223)[0x7fa81ed55c03]
/lib/x86_64-linux-gnu/libclang-cpp.so.12(_ZN5clang14FrontendAction7ExecuteEv+0x56)[0x7fa81f48f456]
/lib/x86_64-linux-gnu/libclang-cpp.so.12(_ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE+0x8b1)[0x7fa81f417331]
/lib/x86_64-linux-gnu/libclang-cpp.so.12(_ZN5clang25ExecuteCompilerInvocationEPNS_16CompilerInstanceE+0x646)[0x7fa81f4f68e6]
clang(_Z8cc1_mainN4llvm8ArrayRefIPKcEES2_Pv+0x9b9)[0x412ab9]
clang[0x410dbf]
/lib/x86_64-linux-gnu/libclang-cpp.so.12(+0x1c1b942)[0x7fa81f11d942]
/lib/x86_64-linux-gnu/libLLVM-12.so.1(_ZN4llvm20CrashRecoveryContext9RunSafelyENS_12function_refIFvvEEE+0xdd)[0x7fa81865b63d]
/lib/x86_64-linux-gnu/libclang-cpp.so.12(_ZNK5clang6driver10CC1Command7ExecuteEN4llvm8ArrayRefINS2_8OptionalINS2_9StringRefEEEEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPb+0x140)[0x7fa81f11d0d0]
/lib/x86_64-linux-gnu/libclang-cpp.so.12(_ZNK5clang6driver11Compilation14ExecuteCommandERKNS0_7CommandERPS3_+0x190)[0x7fa81f0f0b10]
/lib/x86_64-linux-gnu/libclang-cpp.so.12(_ZNK5clang6driver11Compilation11ExecuteJobsERKNS0_7JobListERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0x8a)[0x7fa81f0f0efa]
/lib/x86_64-linux-gnu/libclang-cpp.so.12(_ZN5clang6driver6Driver18ExecuteCompilationERNS0_11CompilationERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0xdc)[0x7fa81f1065cc]
clang(main+0x2529)[0x410629]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fa8174cb083]
clang(_start+0x2e)[0x40ddce]
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Ubuntu clang version 12.0.1-++20211029101322+fed41342a82f-1~exp1~20211029221816.4
Target: bpf
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/pidhide-10b8aa.c
clang: note: diagnostic msg: /tmp/pidhide-10b8aa.sh
clang: note: diagnostic msg:

********************
make: *** [Makefile:62: .output/pidhide.bpf.o] Error 70

**Comment by skyedai910** [comment]
Hi, how did you solve this problem , thx
